#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("FortySevenDeg.SwipeListView.Resource", IsApplication=false)]

namespace FortySevenDeg.SwipeListView
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010004
			public static int choiceOffset = 2130771972;
			
			// aapt resource value: 0x7f010009
			public static int swipeActionLeft = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public static int swipeActionRight = 2130771978;
			
			// aapt resource value: 0x7f010001
			public static int swipeAnimationTime = 2130771969;
			
			// aapt resource value: 0x7f010007
			public static int swipeBackView = 2130771975;
			
			// aapt resource value: 0x7f010005
			public static int swipeCloseAllItemsWhenMoveList = 2130771973;
			
			// aapt resource value: 0x7f01000b
			public static int swipeDrawableChecked = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public static int swipeDrawableUnchecked = 2130771980;
			
			// aapt resource value: 0x7f010006
			public static int swipeFrontView = 2130771974;
			
			// aapt resource value: 0x7f010008
			public static int swipeMode = 2130771976;
			
			// aapt resource value: 0x7f010002
			public static int swipeOffsetLeft = 2130771970;
			
			// aapt resource value: 0x7f010003
			public static int swipeOffsetRight = 2130771971;
			
			// aapt resource value: 0x7f010000
			public static int swipeOpenOnLongPress = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f030001
			public static int both = 2130903041;
			
			// aapt resource value: 0x7f030006
			public static int choice = 2130903046;
			
			// aapt resource value: 0x7f030005
			public static int dismiss = 2130903045;
			
			// aapt resource value: 0x7f030003
			public static int left = 2130903043;
			
			// aapt resource value: 0x7f030000
			public static int none = 2130903040;
			
			// aapt resource value: 0x7f030004
			public static int reveal = 2130903044;
			
			// aapt resource value: 0x7f030002
			public static int right = 2130903042;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f020000
			public static int library_name = 2130837504;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] SwipeListView = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980};
			
			// aapt resource value: 4
			public static int SwipeListView_choiceOffset = 4;
			
			// aapt resource value: 9
			public static int SwipeListView_swipeActionLeft = 9;
			
			// aapt resource value: 10
			public static int SwipeListView_swipeActionRight = 10;
			
			// aapt resource value: 1
			public static int SwipeListView_swipeAnimationTime = 1;
			
			// aapt resource value: 7
			public static int SwipeListView_swipeBackView = 7;
			
			// aapt resource value: 5
			public static int SwipeListView_swipeCloseAllItemsWhenMoveList = 5;
			
			// aapt resource value: 11
			public static int SwipeListView_swipeDrawableChecked = 11;
			
			// aapt resource value: 12
			public static int SwipeListView_swipeDrawableUnchecked = 12;
			
			// aapt resource value: 6
			public static int SwipeListView_swipeFrontView = 6;
			
			// aapt resource value: 8
			public static int SwipeListView_swipeMode = 8;
			
			// aapt resource value: 2
			public static int SwipeListView_swipeOffsetLeft = 2;
			
			// aapt resource value: 3
			public static int SwipeListView_swipeOffsetRight = 3;
			
			// aapt resource value: 0
			public static int SwipeListView_swipeOpenOnLongPress = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
